### ISSUE TITLE
Allow configuration of user object

### ISSUE THREAD

**Issue by mgwidmann** [cpjk/canary#12]
Assuming `current_user` will work for a little bit, but often apps have stuff like `current_user` and `current_admin_user`, ect. It would be nice to be able to configure this globally in `config.exs` as well as override it per plug like `plug :load_resource, model: User, user: :current_admin_user`.

If I have time I'd love to help out on this, for whoever gets to it first...

**Comment by cpjk** [comment]
Good point!

I'll look into this as soon as possible.
