### ISSUE TITLE
remove uneeded using 

### ISSUE THREAD

**Issue by jeregrine** [cpjk/canary#19]
https://github.com/cpjk/canary/blob/master/lib/canary.ex#L4 this using is unnecessary as all it does is import. Update the README and tell user's to just import it :)

**Comment by cpjk** [comment]
Thanks for spotting this! :smile: 

I just pushed a commit to fix this: https://github.com/cpjk/canary/commit/2ea80e9f152f0bfd3c84e9072ae8d7d169b5e97e

**Comment by jeregrine** [comment]
👍💜
