### ISSUE TITLE
Actions :index, :new, :create passes module, not struct

### ISSUE THREAD

**Issue by angeloashmore** [cpjk/canary#20]
When defining abilities for `:index`, `:new`, and `:create`, `_authorize_resource/2` passes the module to `can?/3`, not a struct.

This means defining abilities requires doing this:

``` elixir
def can?(%User{}, action, Item) when action in [:index, :new, :create], do: true
def can?(%User{}, action, %Item{}) when action in [:show], do: true
```

Rather than just:

``` elixir
def can?(%User{}, action, %Item{}) when action in [:index, :new, :create, :show], do: true
```

It makes sense in that at index, new, and create, you have no instance of the model so it would not pass a struct.

Maybe this needs to be mentioned in the docs or change the behavior?

**Comment by angeloashmore** [comment]
Just saw this is mentioned in the `@doc`s, but not in the README. Oops!

**Comment by cpjk** [comment]
Thanks for pointing that out! I'll add it to the README.md as well :smile:.
