### ISSUE TITLE
Tries to preload association on non-existant resource

### ISSUE THREAD

**Issue by angeloashmore** [cpjk/canary#21]
`fetch_resource/2` attempts to preload the provided associations whether the repo is able to retrieve a resource or not.

`repo.get/2` returns nil if the resource does not exist.

This ends up creating the following stacktrace:

``` shell
** (FunctionClauseError) no function clause matching in Ecto.Repo.Preloader.preload/3
stacktrace:
  (ecto) lib/ecto/repo/preloader.ex:35: Ecto.Repo.Preloader.preload(nil, MyApp.Repo, :my_association)
  lib/canary/plugs.ex:82: Canary.Plugs._load_resource/2
  # ...
```

``` elixir
# canary/plugs.ex

defp fetch_resource(conn, opts) do
  repo = Application.get_env(:canary, :repo)

  conn
  |> Map.fetch(resource_name(conn, opts))
  |> case do
    :error ->
      repo.get(opts[:model], conn.params["id"])
      |> preload_if_needed(repo, opts)

    # **Here**:
    {:ok, nil} ->
      repo.get(opts[:model], conn.params["id"])
      |> preload_if_needed(repo, opts)

    {:ok, resource} -> # if there is already a resource loaded onto the nn
      case (resource.__struct__ == opts[:model]) do
        true  ->
          resource
        false ->

          # **And here**:
          repo.get(opts[:model], conn.params["id"])
          |> preload_if_needed(repo, opts)

      end
  end
end
```
## Possible solution

Add a guard in `preload_if_needed/3` when `records` is `nil`.

**Comment by cpjk** [comment]
Thanks for spotting this! I'm looking into it right now.

**Comment by cpjk** [comment]
For posterity, the reason this was not caught was that the tests currently stub out all ecto calls. I'm going to look into possibly converting these to actual calls.

**Comment by cpjk** [comment]
I just pushed https://github.com/cpjk/canary/commit/4c7f4bc1a002fe845c71cf0c9d1c9eff8b0ed9e1, which should fix the issue.

I've also released a patch on hex.

Thanks again for spotting this!

**Comment by angeloashmore** [comment]
Awesome! Thanks for the quick fix.

P.S. Cool avatar!

**Comment by cpjk** [comment]
Haha no problem and thanks! :smile:
