### ISSUE TITLE
Ability to check permission (using canada) based on parent id

### ISSUE THREAD

**Issue by timoteus** [cpjk/canary#23]
I've seen some comments around the codebase concerning `:index` and `:create` actions.

What if you were able to pass the parent id all the way down to the `Canada.Can` implementation so said function can check if `current_user` is authorized to `:create` a resource of type: `for: Type` without an id of `Type`?

This only concerns sub-resources with relations to a parent, i.e., "Can I create a new post based on the thread that post belongs to?" (and current_user of course).

Thoughts? Do tell if I should make myself more clear or if this can already be solved in some other way!

**Comment by timoteus** [comment]
More specifically, I need the id of the parent resource not just a Model in order to authorize `:create` and `:index` actions. 

From `_authorize_resource`:

```
resource = cond do
  action in [:index, :new, :create] ->
    opts[:model]
  true      ->
    fetch_resource(conn, opts)
end
```

**Comment by timoteus** [comment]
This can almost be accomplished using https://github.com/cpjk/canary/pull/22:

```
  plug :load_and_authorize_resource,
    model: Post, id: "post_id",
    only: [:show, :update, :delete]

  plug :authorize_resource,
    model: Thread, id: "thread_id",
    only: [:index, :create]
```

If `_authorize_resource` is changed to always `fetch_resource` that is. 

Only thing missing is a parameter that lets the `Canada.Can` implementation differ from `:index` of different sub resources.

Thoughts appreciated!

**Comment by cpjk** [comment]
I'm not sure that we want to support this. I think that it would be better to authorize on the more conventional URL structure:

e.g. `/threads/:thread_id/posts/:id` in a posts controller rather than authorizing posts (the child) in the threads (the parent) controller within the plug. Rather, I think it would be better to allow the user, if they want, to authorize on the child within a parent action using the `Canada.Can.can?/3` function. 

However, that is just my own opinion, and I'm of course open for discussion :smile:

**Comment by timoteus** [comment]
I don't see how it solves my problem though, would you care to elaborate? Specifically for the actions with no child id, e.g., `POST /threads/:thread_id/posts` and `GET /threads/:thread_id/posts`.

**Comment by cpjk** [comment]
Ah, sorry man. I misread the first comment in this issue :sweat_smile:. I think I understand the reasoning behind this now. Please disregard my last comment. I'll look at your PR as soon as possible!

**Comment by cpjk** [comment]
Closing  this as the conversation is dead.
