### ISSUE TITLE
Please provide more information as how to implement this library inside Phoenix

### ISSUE THREAD

**Issue by acrolink** [cpjk/canary#42]
Can be great with a sample Phoenix application :+1: Thank you.

**Comment by cpjk** [comment]
Hey, I have a simple (very incomplete) blog project [here](https://github.com/cpjk/brog) that uses Canary for authorization. I think there's also a blog post floating around about using Canary with Phoenix. The README.md for Canary also contains some examples for specific features.

**Comment by cpjk** [comment]
I'm updating the README right now to include a more concrete example of the basic requirements to get up and running.

**Comment by acrolink** [comment]
@cpjk Thank you very much.. I am new to Phoenix and what I have managed to do so far in my project is to establish some content-owner relationships, with simple checks I give authorization to the user to modify/delete/view the content if he is the owner of the particular entity. Of course, using a module like canary can make this an easier task to implement and maintain. Thank you :+1: 

P.S. Phoenix/Elixir looks really impressing, both in terms of language and performance. I have used several frameworks over the years, and I anticipate that Phoenix will take larger part in big scale web projects in the future.

**Comment by cpjk** [comment]
Always awesome to see someone excited about Elixir! It is a great language with a fantastic community. I've updated the README.md to make the minimum requirements more clear.

**Comment by cpjk** [comment]
If you have more questions, the elixir-lang slack team is a great place to ask about anything elixir-related.  If you have any ideas about how to make the README more clear, or want to write about your experiences setting up Canary in order to to help others, that would be awesome! I'm closing this issue now.
