### ISSUE TITLE
Channels example? 

### ISSUE THREAD

**Issue by niccolox** [cpjk/canary#53]
hi

does Canary support Channels? 

would it be possible to have an example in the plug test file?

I asked this on Canada and its apparently possible
https://github.com/jarednorman/canada/issues/14

**Comment by cpjk** [comment]
I haven't tested canary with channels yet. Canary is mostly intended for simple CRUD applications. If you want to do anything more advanced, I would suggest implementing your own plug-based authorization.

I'm interested to hear if it is possible though!

**Comment by niccolox** [comment]
tx
