### ISSUE TITLE
Compile warnings for elixir 1.4

### ISSUE THREAD

**Issue by developerworks** [cpjk/canary#58]
```
warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name

```

**Comment by cpjk** [comment]
I just pushed the latest master to hex.pm. The warnings should now be fixed if you fetch canary 1.1.1 from hex. Closing the issue but feel free to reopen the issue if the problem persists after fetching the latest version.
