### ISSUE TITLE
non_id_actions option on Hex

### ISSUE THREAD

**Issue by speeddragon** [cpjk/canary#59]
Shouldn't :non_id_actions option be on Hex documentation ? There is a reference on the Readme but nothing on Hex.

**Comment by cpjk** [comment]
Addressed in https://github.com/cpjk/canary/pull/64. Take a look and I'll merge. Sorry for the long wait. I've been busy IRL.

**Comment by cpjk** [comment]
Addressed in https://github.com/cpjk/canary/pull/64
