### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by jeroenbourgois** [cpjk/canary#70]
Hi

Would you accept a PR regarding the readme? Getting started on Phoenix was not that clear to me and I bumped into some issues. Be happy do document a bit to get other users up and running. What do you think?

**Comment by cpjk** [comment]
Sure, that would be great! :smile:

**Comment by jeroenbourgois** [comment]
Sorry, this can be closed, I can no longer remember what was unclear. Happy canary user ever since!
